### ISSUE TITLE
Is screen.c missing?

### ISSUE THREAD

**Issue by neozeed** [pcercuei/glfrontier#5]
I'm trying to build on MinGW and the makefiles (both Makefile-i386 & Makefile-mingw) both reference a screen.c that is missing.

**Comment by pcercuei** [comment]
Does it work with Makefile-C?

**Comment by neozeed** [comment]
I thought it had crashed, turns out it takes forever to generate the 535 split C files for the C version..  Maybe have as68k be a little more verbose?

I had to fight the linker a good bit, SDL_image although mentioned in the makefile wasn't needed.

digging a little more I got the i386 to build, in hostcall.c I had to comment out #include "../host.h"

and of course copy the SRCOBJS define from the C makefile, without host.o naturally.

thanks!

**Comment by neozeed** [comment]
no wait, I see sdl_image as part of the software only renderer, for loading the mouse cursor..  I thought it flipped between them not blitting onto a GL surface in the 3d one.

**Comment by pcercuei** [comment]
It's very possible that it does not build anymore, I didn't touch that project in like 5 years :')

**Comment by neozeed** [comment]
I haven't messed with it in over 10 years, when I somehow managed to get it running (poorly) under NeXTSTEP.

Id just ran into [this tutorial](https://www.youtube.com/watch?v=srlJVE50mCI&list=PL9E1E1F7AA6193498) on how to actually play the game properly (I had it for PC & Amiga in the day and really sucked) and was inspired.

I managed to get the older frontvm, frontvm2 & frontvm3 running but saw your repo with more updates!

Thanks again!

**Comment by neozeed** [comment]
OH, yeah let me close this! thanks again!
